// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1
// source: mov.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcode      int32   `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	CharacterID []byte  `protobuf:"bytes,2,opt,name=characterID,proto3" json:"characterID,omitempty"`
	X           float64 `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y           float64 `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Z           float64 `protobuf:"fixed64,5,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Movement) Reset() {
	*x = Movement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mov_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_mov_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_mov_proto_rawDescGZIP(), []int{0}
}

func (x *Movement) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *Movement) GetCharacterID() []byte {
	if x != nil {
		return x.CharacterID
	}
	return nil
}

func (x *Movement) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Movement) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Movement) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_mov_proto protoreflect.FileDescriptor

var file_mov_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x6e, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x7a, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mov_proto_rawDescOnce sync.Once
	file_mov_proto_rawDescData = file_mov_proto_rawDesc
)

func file_mov_proto_rawDescGZIP() []byte {
	file_mov_proto_rawDescOnce.Do(func() {
		file_mov_proto_rawDescData = protoimpl.X.CompressGZIP(file_mov_proto_rawDescData)
	})
	return file_mov_proto_rawDescData
}

var file_mov_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mov_proto_goTypes = []interface{}{
	(*Movement)(nil), // 0: main.Movement
}
var file_mov_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mov_proto_init() }
func file_mov_proto_init() {
	if File_mov_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mov_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mov_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mov_proto_goTypes,
		DependencyIndexes: file_mov_proto_depIdxs,
		MessageInfos:      file_mov_proto_msgTypes,
	}.Build()
	File_mov_proto = out.File
	file_mov_proto_rawDesc = nil
	file_mov_proto_goTypes = nil
	file_mov_proto_depIdxs = nil
}
